/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;
 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import tabel.DataSM;
import tabel.TabelDataSM;
 
/**
 *
 * @author Ita Masita
 */
public class AgendaSM extends javax.swing.JFrame {
 
    private TabelDataSM ModelTSM;
    private Connection koneksi;
    private Statement kode;
 
    /**
     * Creates new form AgendaSM
     */
    public AgendaSM() {
        initComponents();
 
        ModelTSM = new TabelDataSM();
        tabelSM.setModel(ModelTSM);
 
        koneksiDb();
        tampil();
 
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
 
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSM = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox();
        cari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        close1 = new javax.swing.JButton();
        txtTgl = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtNoSurat = new javax.swing.JTextField();
        txtTglSurat = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtDari = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtIsi = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtKet = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
 
        setTitle("Agenda Surat Masuk");
        setResizable(false);
 
        jPanel1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 700));
 
        tabelSM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tabelSM.setPreferredSize(new java.awt.Dimension(400, 192));
        tabelSM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelSMMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSM);
        tabelSM.getColumnModel().getColumn(1).setPreferredWidth(40);
 
        jPanel4.setBackground(new java.awt.Color(204, 102, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Pencarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), java.awt.Color.white)); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
 
        jLabel11.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11.setText("Cari berdasarkan:");
 
        cmbCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nomor Surat", "Tanggal Surat", "Perihal" }));
 
        cari.setFont(new java.awt.Font("Tahoma", 0, 12));
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
 
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Inspector.png"))); // NOI18N
 
        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addGap(216, 216, 216))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
 
        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(574, 400));
 
        jLabel20.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tanggal Terima");
 
        jLabel21.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Nomor");
 
        jLabel22.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":");
 
        jLabel23.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
 
        txtNo.setFont(new java.awt.Font("Tahoma", 0, 14));
 
        close1.setFont(new java.awt.Font("Tahoma", 1, 14));
        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close_button_delete_terminate_error_quit_exit_cancel_ok.png"))); // NOI18N
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
 
        txtTgl.setDateFormatString("dd-MMM-yyyy");
        txtTgl.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtTgl.setMaxSelectableDate(null);
 
        jPanel5.setBackground(new java.awt.Color(204, 102, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Surat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
 
        jLabel24.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("No. Surat");
 
        jLabel25.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");
 
        txtNoSurat.setFont(new java.awt.Font("Tahoma", 0, 14));
 
        txtTglSurat.setDateFormatString("dd-MMM-yyyy");
        txtTglSurat.setFont(new java.awt.Font("Tahoma", 0, 12));
 
        jLabel26.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Tanggal Surat");
 
        jLabel27.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(":");
 
        jLabel28.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Terima dari");
 
        jLabel29.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText(":");
 
        txtDari.setFont(new java.awt.Font("Tahoma", 0, 14));
 
        jLabel30.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Isi Perihal");
 
        jLabel31.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(":");
 
        txtIsi.setFont(new java.awt.Font("Tahoma", 0, 14));
 
        jLabel32.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Lampiran");
 
        jLabel33.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(":");
 
        txtDir.setFont(new java.awt.Font("Tahoma", 0, 12));
 
        jLabel34.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Keterangan");
 
        jLabel35.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText(":");
 
        txtKet.setFont(new java.awt.Font("Tahoma", 0, 14));
 
        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(jLabel34))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTglSurat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNoSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKet, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDir)
                            .addGap(35, 35, 35))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIsi, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDari, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(txtNoSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtTglSurat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(txtDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(txtIsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(txtKet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
 
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon_paper.png"))); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
 
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
 
        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(delete)
                        .addGap(18, 18, 18)
                        .addComponent(close1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel21))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel22))
                            .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
 
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Preview.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
 
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(183, 183, 183))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
 
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
 
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1097)/2, (screenSize.height-617)/2, 1097, 617);
    }// </editor-fold>
 
    private void tabelSMMousePressed(java.awt.event.MouseEvent evt) {
        tabel();
        // TODO add your handling code here:
    }
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String url = "jdbc:mysql://localhost/surat_db";
        String username = "root";
        String npassword = "";
 
        String reportSource = "D:\\Docs\\Data Kuliah\\ITB Batch 8\\TMD11\\TugasBesar_RWS\\src\\admin\\SM.jrxml";
 
        Map<String, Object> params = new HashMap<>();
 
        try {
            Class.forName("com.mysql.jdbc.Driver");
 
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
 
        }
 
        koneksi = null;
        try {
            koneksi = (Connection) DriverManager.getConnection(url, username, npassword);
        } catch (SQLException ex) {
            Logger.getLogger(AgendaSM.class.getName()).log(Level.SEVERE, null, ex);
 
        }
 
        try {
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, koneksi);
            JasperViewer.viewReport(jasperPrint);
        } catch (JRException ex) {
            Logger.getLogger(AgendaSM.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        // TODO add your handling code here:
    }
 
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {
        delete();
        // TODO add your handling code here:
    }
 
    private void editActionPerformed(java.awt.event.ActionEvent evt) {
 
        int app;
        if ((app = JOptionPane.showConfirmDialog(null, "Ubah data surat?", "", JOptionPane.YES_NO_OPTION)) == 0) {
            try {
                String tampilan = "dd-MMM-yyyy";
                SimpleDateFormat format = new SimpleDateFormat(tampilan);
                String tanggal = String.valueOf(format.format(txtTgl.getDate()));
                String tanggal2 = String.valueOf(format.format(txtTglSurat.getDate()));
                String sql = "UPDATE tb_masuk SET"
                + " tgl = '" + tanggal + "',"
                + " no = '" + txtNo.getText() + "',"
                + " tgl_surat = '" + tanggal2 + "',"
                + " dari = '" + txtDari.getText() + "',"
                + " isi = '" + txtIsi.getText() + "',"
                + " lampiran = '" + txtDir.getText() + "',"
                + " ket = '" + txtKet.getText() + "' WHERE"
                + " no_surat = '" + txtNoSurat.getText() + "'";
 
                kode.executeUpdate(sql);
                tampil();
                JOptionPane.showMessageDialog(null, "Data surat berhasil diubah.");
                clear();
 
            } catch (SQLException ex) {
                System.err.print(ex);
            }
        }
        // TODO add your handling code here:
    }
 
    private void closeActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        // TODO add your handling code here:
    }
 
    private void cariKeyReleased(java.awt.event.KeyEvent evt) {
        find();
        // TODO add your handling code here:
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaSM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
 
            @Override
            public void run() {
                new AgendaSM().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JTextField cari;
    private javax.swing.JButton close1;
    private javax.swing.JComboBox cmbCari;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelSM;
    private javax.swing.JTextField txtDari;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtIsi;
    private javax.swing.JTextField txtKet;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtNoSurat;
    private com.toedter.calendar.JDateChooser txtTgl;
    private com.toedter.calendar.JDateChooser txtTglSurat;
    // End of variables declaration
 
    private void koneksiDb() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            koneksi = DriverManager.getConnection("jdbc:mysql://localhost/surat_db", "root", "");
            kode = koneksi.createStatement();
        } catch (SQLException | ClassNotFoundException ex) {
            System.err.print(ex);
        }
    }
 
    private void tampil() {
       tabelSM.setModel(ModelTSM);
        int baris = tabelSM.getRowCount();
            for (int i = 0; i < baris; i++) {
                ModelTSM.delete(0, baris);
            }
        try {
            String sql = "SELECT * FROM tb_masuk";
            ResultSet result = kode.executeQuery(sql);
 
            while (result.next()) {
                DataSM sm = new DataSM();
                sm.setTgl(result.getString(1));
                sm.setNo(result.getString(2));
                sm.setNo_Surat(result.getString(3));
                sm.setTgl_Surat(result.getString(4));
                sm.setDari(result.getString(5));
                sm.setIsi(result.getString(6));
                sm.setLampiran(result.getString(7));
                sm.setKet(result.getString(8));
 
                ModelTSM.add(sm);
            }
 
        } catch (SQLException ex) {
            System.err.print(ex);
        }
    }
 
    private void tabel() {
        tabelSM.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
 
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int baris = tabelSM.getSelectedRow();
 
                if (baris != -1) {
                    DataSM sm = ModelTSM.get(baris);
                    try {
                        DateFormat df = new SimpleDateFormat("dd-MMM-yyyy");
                        String tanggala = sm.getTgl();
                        Date tanggal = new Date(df.parse(tanggala.substring(0)).getTime());
                        String tanggalb = sm.getTgl_Surat();
                        Date tanggal2 = new Date(df.parse(tanggalb.substring(0)).getTime());
 
                        txtTgl.setDate(tanggal);
                        txtNo.setText(sm.getNo());
                        txtTglSurat.setDate(tanggal2);
                        txtNoSurat.setText(sm.getNo_Surat());
                        txtDari.setText(sm.getDari());
                        txtIsi.setText(sm.getIsi());
                        txtDir.setText(sm.getLampiran());
                        txtKet.setText(sm.getKet());
                    } catch (ParseException ex) {
                        Logger.getLogger(AgendaSM.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }
 
    private void delete() {
        int app, help;
        if ((app = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data?", "Perhatian!", JOptionPane.YES_NO_OPTION)) == 0) {
            try {
                String sql = "DELETE FROM tb_masuk WHERE"
                        + " no_surat = '" + txtNoSurat.getText() + "'";
                help = kode.executeUpdate(sql);
                tampil();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                cari.setText(null);
            } catch (SQLException ex) {
                System.err.print(ex);
            }
        }
    }
 
    private void find() {
       int baris = tabelSM.getRowCount();
       for(int i=0; i<baris; i++){
            ModelTSM.delete(i, baris);
       }
 
        String bantu;
        if (cmbCari.getSelectedItem().equals("Nomor Surat")) {
            bantu = "no_surat";
        } else if (cmbCari.getSelectedItem().equals("Tanggal Surat")) {
            bantu = "tgl_surat";
        } else {
            bantu = "isi";
        }
 
        try {
            String sql = "SELECT * FROM tb_masuk WHERE " + bantu + " like '%"+cari.getText()+"%'";
            kode = koneksi.createStatement();
 
            ResultSet rs = kode.executeQuery(sql);
 
            while (rs.next()){
                DataSM sm = new DataSM();
 
                sm.setTgl(rs.getString(1));
                sm.setNo(rs.getString(2));
                sm.setNo_Surat(rs.getString(3));
                sm.setTgl_Surat(rs.getString(4));
                sm.setDari(rs.getString(5));
                sm.setIsi(rs.getString(6));
                sm.setLampiran(rs.getString(7));
                sm.setKet(rs.getString(8));
 
                ModelTSM.add(sm);
            }
 
        } catch (SQLException ex) {
            Logger.getLogger(AgendaSM.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }
 
    private void clear() {
        txtTgl.setDate(null);
        txtNo.setText(null);
        txtTglSurat.setDate(null);
        txtNoSurat.setText(null);
        txtDari.setText(null);
        txtIsi.setText(null);
        txtDir.setText(null);
        txtKet.setText(null);
    }
}